# Generated by Django 2.0.5 on 2018-11-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20180713_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_image',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_type',
            field=models.TextField(default='normal'),
            preserve_default=False,
        ),
    ]
