# Generated by Django 2.0.5 on 2018-07-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesfromxml', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
