# Generated by Django 2.0.5 on 2018-07-13 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notesfromxml', '0002_auto_20180712_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.TextField(blank=True)),
                ('image_text', models.TextField(blank=True)),
                ('image_picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ImageDocumentMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notesfromxml.Document')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notesfromxml.Image')),
            ],
        ),
        migrations.CreateModel(
            name='ImageTagMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notesfromxml.Image')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notesfromxml.Tag')),
            ],
        ),
    ]
