name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.DEFAULT_USER_KEY }}
            HOSTNAME: ${{secrets.EINSKIS_IP}}
            USER_NAME: ${{secrets.DEFAULT_USER_FOR_AWS}}
            DEPLOY_USER_NAME: ${{secrets.DEPLOY_USER_NAME}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              #restart using whatever script I have created for that purpose
              ./pull-master-notemaster-as-euro-counter.sh &&
              ./restart-notemaster.sh
              '
